export const PERMISSIONS = {
  view_products: "view_products",
  add_to_cart: "add_to_cart",
  checkout: "checkout",
  view_orders: "view_orders",
  create_review: "create_review",
  edit_profile: "edit_profile",
  create_shop: "create_shop",

  // Shop/Seller Permissions (matching backend Permission enum)
  manage_product: "manage_product",
  manage_order: "manage_order",
  view_dashboard: "view_dashboard",
  manage_shop_staff: "manage_shop_staff",
  edit_profile_shop: "edit_profile_shop",
  chat_with_customer: "chat_with_customer",
  try_on_tester: "try_on_tester",
  manage_shop_setting: "manage_shop_setting",
  view_shop_tutorial: "view_shop_tutorial",

  view_shop_orders: "view_shop_orders",
  update_order_status: "update_order_status",
  moderate_reviews: "moderate_reviews",

  view_users: "view_users",
  create_user: "create_user",
  update_user: "update_user",
  delete_user: "delete_user",
  manage_users: "manage_users",
  manage_roles: "manage_roles",
  manage_permissions: "manage_permissions",
  moderate_posts: "moderate_posts",
  moderate_products: "moderate_products",
  view_system_logs: "view_system_logs",
  manage_coupons: "manage_coupons",
  manage_brands: "manage_brands",
  manage_categorys: "manage_categorys",
  manage_shop_address: "manage_shop_address",

  create_post: "create_post",
  edit_post: "edit_post",
  delete_post: "delete_post",
  create_comment: "create_comment",
  edit_comment: "edit_comment",
  delete_comment: "delete_comment",
  toggle_like: "toggle_like",
  toggle_follow: "toggle_follow",
  manage_addresses: "manage_addresses",
} as const;
